version: "3.9"

services:
  proxy:
    image: nginx:alpine
    container_name: aurum_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
      - api
    restart: unless-stopped

  web:
    build: .
    container_name: aurum_frontend
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  api:
    build: ../API
    container_name: aurum_backend
    env_file:
      - ../API/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
